// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plugins.DataStore.SQL;

#nullable disable

namespace Plugins.DataStore.SQL.Migrations
{
    [DbContext(typeof(FarmContext))]
    [Migration("20251218165642_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreBusiness.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.HasIndex("FarmId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 12,
                            FarmId = 1,
                            HealthStatus = "Khỏe mạnh",
                            Name = "Heo 01",
                            Species = "Heo"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 24,
                            FarmId = 2,
                            HealthStatus = "Khỏe mạnh",
                            Name = "Bò 01",
                            Species = "Bò"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("FarmId");

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            FarmId = 1,
                            Address = "Hà Nội",
                            Name = "Trại Heo Ba Vì",
                            OwnerName = "Nguyễn Văn A",
                            PhoneNumber = ""
                        },
                        new
                        {
                            FarmId = 2,
                            Address = "Sơn La",
                            Name = "Trại Bò Mộc Châu",
                            OwnerName = "Trần Thị B",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("CoreBusiness.Animal", b =>
                {
                    b.HasOne("CoreBusiness.Farm", "Farm")
                        .WithMany("Animals")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("CoreBusiness.Farm", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
